# Generated by Django 6.0 on 2026-01-04 17:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, max_length=50, verbose_name='Género')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Foto')),
                ('why_train', models.TextField(blank=True, verbose_name='¿Por qué quiere entrenar?')),
                ('expectations', models.TextField(blank=True, verbose_name='¿Qué espera lograr?')),
                ('fears', models.TextField(blank=True, verbose_name='¿Qué le preocupa o le da miedo del ejercicio?')),
                ('process_explanation', models.TextField(blank=True, verbose_name='Explicación del proceso de entrenamiento (entrenador)')),
                ('sport_practiced', models.CharField(blank=True, max_length=100, verbose_name='Deporte practicado')),
                ('time_practicing', models.CharField(blank=True, max_length=100, verbose_name='Tiempo de práctica')),
                ('stage', models.CharField(blank=True, choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Semi-entrenado', 'Semi-entrenado'), ('Entrenado', 'Entrenado')], max_length=50, verbose_name='Etapa')),
                ('weekly_sessions', models.IntegerField(default=0, verbose_name='Sesiones semanales')),
                ('sports_observations', models.TextField(blank=True, verbose_name='Observaciones deportivas')),
                ('main_goal', models.TextField(blank=True, verbose_name='Objetivo principal')),
                ('secondary_goals', models.TextField(blank=True, verbose_name='Objetivos secundarios')),
                ('trainer_goals', models.TextField(blank=True, verbose_name='Objetivos del Entrenador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('contact_info', models.TextField(help_text='Phone, Email, etc.')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='trainers/')),
            ],
        ),
        migrations.CreateModel(
            name='ClientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='client_progress/')),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha de control')),
                ('height', models.DecimalField(decimal_places=2, help_text='Metros', max_digits=4, verbose_name='Talla (m)')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Kg', max_digits=5, verbose_name='Peso (kg)')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC')),
                ('imc_category', models.CharField(blank=True, max_length=100, verbose_name='Categoría IMC')),
                ('fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de grasa corporal (%)')),
                ('colmen_fat_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masa libre de grasa (kg)')),
                ('obesity_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de obesidad (Sí / No)')),
                ('anthropometry_observations', models.TextField(blank=True, verbose_name='Observaciones Antropométricas')),
                ('rm_date', models.DateField(blank=True, null=True, verbose_name='Fecha de control RM')),
                ('squat_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Sentadilla (Smith) (kg)')),
                ('bench_press_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Press banca plano (kg)')),
                ('hip_thrust_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Hip thrust (kg)')),
                ('vertical_row_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Remo vertical (kg)')),
                ('deadlift_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso muerto (kg)')),
                ('evaluations_done', models.TextField(blank=True, help_text='ej. FMS, pliegues cutáneos', verbose_name='Evaluaciones realizadas')),
                ('additional_comments', models.TextField(blank=True, verbose_name='Comentarios adicionales')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='core.client')),
            ],
        ),
    ]
