# Generated by Django 6.0 on 2026-01-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Centímetros', max_digits=5, verbose_name='Talla (cm)'),
        ),
    ]
