# Generated by Django 6.0 on 2026-01-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_measurement_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='instagram_profile',
            field=models.URLField(blank=True, verbose_name='Perfil de Instagram'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='tiktok_profile',
            field=models.URLField(blank=True, verbose_name='Perfil de TikTok'),
        ),
    ]
