# Generated by Django 6.0 on 2026-01-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trainer_instagram_profile_trainer_tiktok_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Breve descripción para el pie de página', verbose_name='Descripción de la empresa')),
                ('instagram_profile', models.URLField(blank=True, verbose_name='Perfil de Instagram')),
                ('tiktok_profile', models.URLField(blank=True, verbose_name='Perfil de TikTok')),
            ],
        ),
    ]
