# Generated by Django 6.0 on 2026-01-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_businessprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='instagram_profile',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='tiktok_profile',
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono / Celular'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='contact_info',
            field=models.TextField(blank=True, help_text='Dirección, Ciudad, etc.'),
        ),
    ]
