# Generated by Django 6.0 on 2026-01-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_trainer_instagram_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='activity_level',
            field=models.CharField(choices=[('1.2', 'Sedentario (poco o nada ejercicio)'), ('1.375', 'Ligera (1-3 días/sem)'), ('1.55', 'Moderada (3-5 días/sem)'), ('1.725', 'Intensa (6-7 días/sem)'), ('1.9', 'Muy Intensa (doble sesión)')], default='1.2', max_length=10, verbose_name='Nivel de Actividad'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='basal_metabolic_rate',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Kcal', max_digits=6, null=True, verbose_name='Tasa Metabólica Basal (MB)'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='total_caloric_expenditure',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Kcal', max_digits=6, null=True, verbose_name='Gasto Calórico Total (GCT)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10, verbose_name='Género'),
        ),
    ]
