# Generated by Django 6.0 on 2026-05-10 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_measurement_activity_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_per', models.CharField(max_length=50, verbose_name='Nombre del Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, verbose_name='Nombre del Rol')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='entrenador_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to='core.trainer'),
        ),
        migrations.AddField(
            model_name='client',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.profile'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='core.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='core.role'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rut', models.CharField(max_length=50, verbose_name='Nombre de Ruta')),
                ('url_rut', models.CharField(max_length=100, verbose_name='URL')),
                ('nodo_rut', models.CharField(max_length=1, verbose_name='Nodo')),
                ('orden_rut', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Orden')),
                ('padre_rut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subrutas', to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora de la Sesión')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.client')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha Programada (12h antes)')),
                ('estado_envio', models.BooleanField(default=False, verbose_name='Enviado')),
                ('tipo_notif', models.CharField(default='E-mail', max_length=20, verbose_name='Tipo de Notificación')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserta_acc', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1, verbose_name='Permiso Insertar')),
                ('update_acc', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1, verbose_name='Permiso Actualizar')),
                ('delete_acc', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1, verbose_name='Permiso Borrar')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='core.profile')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='core.route')),
            ],
            options={
                'unique_together': {('perfil', 'ruta')},
            },
        ),
    ]
